logging:
  path: /usr/log/xzs/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xzs?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: xzs
    password: xzs123
    driver-class-name: com.mysql.cj.jdbc.Driver
